---
  equidistant_proj4: "+proj=aeqd +lat_0=35 +lon_0=105 +x_0=0 +y_0=0 +ellps=WGS84 +datum=WGS84 +units=m +no_defs"
  equalarea_proj4: "+proj=aea +lat_1=27 +lat_2=45 +lat_0=35 +lon_0=105 +x_0=0 +y_0=0 +ellps=WGS84 +datum=WGS84 +units=m +no_defs"
  country_name: "China"
  country_bbox: # Defines boundary box (x_min , x_max , y_min , y_max) to crop nightlights image
    -  69 # x_min / lower longitude
    - 140 # x_max / upper longitude
    -  15 # y_min / lower latitude
    -  58 # y_max / upper latitude
  geo_name: "townships"
  geo_key: "gbcode"
  geo_shapefile: "../input/townships_2000_epsg4326.shp"
  year: 2000
  brightness: 30
  raster_download: TRUE
  # graphic zoom box (optional)
  zoom_bbox: # Optional argument to specify area depicted in optional maps (e.g., Shanghai area in DMD's Figure 1)
    - 119.00 # x_min / lower longitude
    - 122.50 # x_max / upper longitude
    -  30.25 # y_min / lower latitude
    -  32.75 # y_max / upper latitude
